name: CI

on:
  push:

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php:
          - "7.4"
        wpmu:
          - "0"
          - "1"
        wordpress:
          - "5.8"
          - latest
          - trunk
    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=5s --health-retries=5
    steps:
      - name: Check out source code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0

      - name: Set up PHP
        uses: shivammathur/setup-php@448bd61c6fe9db2113173467e4c22b87ddc2971a # tag=2.18.1
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        uses: ramsey/composer-install@2.1.0

      - name: Verify MariaDB connection
        run: |
          while ! mysqladmin ping -h 127.0.0.1 -P ${{ job.services.mysql.ports[3306] }} --silent; do
            sleep 1
          done
        timeout-minutes: 3

      - name: Install WP Test Suite
        run: ./.github/install-wp-tests.sh wordpress_test root root 127.0.0.1:${{ job.services.mysql.ports[3306] }} ${{ matrix.wordpress }}

      - name: Install PHPUnit polyfills
        run: composer require --dev  --prefer-dist --no-progress --no-interaction yoast/phpunit-polyfills

      - name: Run tests
        run: vendor/bin/phpunit
        env:
          WP_MULTISITE: ${{ matrix.wpmu }}
